# Predictive Forecasting of Care Load & Placement Demand

## U.S. Department of Health and Human Services (HHS)

### Notebook 01: Data Understanding

---

### Project Objective

The objective of this notebook is to perform the initial understanding of the Unaccompanied Alien Children (UAC) dataset. This includes loading the dataset, understanding its structure, identifying variables, checking data quality, and preparing the foundation for Exploratory Data Analysis (EDA) and predictive forecasting.

---

### Author

Kishan Masura

---

### Notebook Goals

- Load the dataset
- Understand each column
- Verify data types
- Check dataset dimensions
- Identify missing values
- Generate descriptive statistics
- Prepare for Exploratory Data Analysis

In [1]:
import pandas as pd
import numpy as np

In [2]:
# ==========================================
# Load Dataset
# ==========================================

import pandas as pd

df = pd.read_csv("../data/raw/HHS_Unaccompanied_Alien_Children_Program.csv")

df.head()

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,"December 21, 2025",6.0,18.0,11.0,"2,484",14.0
1,"December 18, 2025",11.0,50.0,6.0,"2,472",16.0
2,"December 17, 2025",7.0,31.0,11.0,"2,481",10.0
3,"December 16, 2025",8.0,54.0,15.0,"2,468",9.0
4,"December 15, 2025",11.0,42.0,9.0,"2,470",7.0

# Predictive Forecasting of Care Load & Placement Demand

## Notebook 01 – Data Understanding

### Objective

Understand the dataset before performing any cleaning or analysis.

Tasks:

- View dataset
- Understand shape
- Check data types
- Identify missing values
- Review summary statistics

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../data/raw/HHS_Unaccompanied_Alien_Children_Program.csv")

df.head()

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,"December 21, 2025",6.0,18.0,11.0,"2,484",14.0
1,"December 18, 2025",11.0,50.0,6.0,"2,472",16.0
2,"December 17, 2025",7.0,31.0,11.0,"2,481",10.0
3,"December 16, 2025",8.0,54.0,15.0,"2,468",9.0
4,"December 15, 2025",11.0,42.0,9.0,"2,470",7.0

In [5]:
df.shape

(1170, 6)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1170 entries, 0 to 1169
Data columns (total 6 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Date                                             720 non-null    str
 1   Children apprehended and placed in CBP custody*  720 non-null    float64
 2   Children in CBP custody                          720 non-null    float64
 3   Children transferred out of CBP custody          720 non-null    float64
 4   Children in HHS Care                             720 non-null    str
 5   Children discharged from HHS Care                720 non-null    float64
dtypes: float64(4), str(2)
memory usage: 55.0 KB

In [7]:
df.describe()

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children discharged from HHS Care
count,720.000000,720.000000,720.000000,720.000000
mean,93.523611,171.494444,128.668056,173.406944
std,72.646625,126.354965,97.322012,125.702841
min,0.000000,7.000000,0.000000,0.000000
25%,12.000000,36.000000,14.000000,19.750000
50%,99.000000,193.000000,157.000000,181.000000
75%,147.250000,263.250000,199.250000,267.000000
max,333.000000,531.000000,440.000000,505.000000

In [8]:
df.columns

Index(['Date', 'Children apprehended and placed in CBP custody*',
       'Children in CBP custody', 'Children transferred out of CBP custody',
       'Children in HHS Care', 'Children discharged from HHS Care'],
      dtype='str')

In [9]:
df.dtypes

Date                                                   str
Children apprehended and placed in CBP custody*    float64
Children in CBP custody                            float64
Children transferred out of CBP custody            float64
Children in HHS Care                                   str
Children discharged from HHS Care                  float64
dtype: object

In [10]:
df.isnull().sum()

Date                                               450
Children apprehended and placed in CBP custody*    450
Children in CBP custody                            450
Children transferred out of CBP custody            450
Children in HHS Care                               450
Children discharged from HHS Care                  450
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(449)

In [12]:
df.sample(10)

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
316,"September 10, 2024",131.0,251.0,180.0,"6,396",148.0
491,"December 27, 2023",74.0,103.0,80.0,"11,206",335.0
611,"June 29, 2023",81.0,213.0,153.0,"6,058",213.0
251,"December 12, 2024",153.0,253.0,286.0,"6,481",194.0
620,"June 15, 2023",91.0,75.0,97.0,"6,038",272.0
338,"August 06, 2024",163.0,283.0,200.0,"5,998",143.0
912,NaN,NaN,NaN,NaN,NaN,NaN
623,"June 12, 2023",84.0,118.0,136.0,"6,021",177.0
481,"January 11, 2024",29.0,51.0,11.0,"8,829",476.0
773,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df[df.isnull().all(axis=1)]

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
720,NaN,NaN,NaN,NaN,NaN,NaN
721,NaN,NaN,NaN,NaN,NaN,NaN
722,NaN,NaN,NaN,NaN,NaN,NaN
723,NaN,NaN,NaN,NaN,NaN,NaN
724,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
1165,NaN,NaN,NaN,NaN,NaN,NaN
1166,NaN,NaN,NaN,NaN,NaN,NaN
1167,NaN,NaN,NaN,NaN,NaN,NaN
1168,NaN,NaN,NaN,NaN,NaN,NaN
1169,NaN,NaN,NaN,NaN,NaN,NaN