# Notebook 02 – Data Cleaning

## Objective

Clean the raw HHS dataset before Exploratory Data Analysis (EDA) and forecasting.

Tasks

- Remove completely empty rows
- Remove duplicate rows
- Convert data types
- Save cleaned dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/HHS_Unaccompanied_Alien_Children_Program.csv")

df.head()

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,"December 21, 2025",6.0,18.0,11.0,"2,484",14.0
1,"December 18, 2025",11.0,50.0,6.0,"2,472",16.0
2,"December 17, 2025",7.0,31.0,11.0,"2,481",10.0
3,"December 16, 2025",8.0,54.0,15.0,"2,468",9.0
4,"December 15, 2025",11.0,42.0,9.0,"2,470",7.0

In [3]:
df = df.dropna(how="all")

In [4]:
df.shape

(720, 6)

## Step 2 - Verify Cleaning

In [5]:
df.isnull().sum()

Date                                               0
Children apprehended and placed in CBP custody*    0
Children in CBP custody                            0
Children transferred out of CBP custody            0
Children in HHS Care                               0
Children discharged from HHS Care                  0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.dtypes

Date                                                   str
Children apprehended and placed in CBP custody*    float64
Children in CBP custody                            float64
Children transferred out of CBP custody            float64
Children in HHS Care                                   str
Children discharged from HHS Care                  float64
dtype: object

In [8]:
df.isnull().sum()

Date                                               0
Children apprehended and placed in CBP custody*    0
Children in CBP custody                            0
Children transferred out of CBP custody            0
Children in HHS Care                               0
Children discharged from HHS Care                  0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

## Step 3 - Convert Date Column

In [10]:
df["Date"] = pd.to_datetime(df["Date"])

In [11]:
df.dtypes

Date                                               datetime64[us]
Children apprehended and placed in CBP custody*           float64
Children in CBP custody                                   float64
Children transferred out of CBP custody                   float64
Children in HHS Care                                          str
Children discharged from HHS Care                         float64
dtype: object

## Step 4 - Convert Children in HHS Care to Numeric

In [12]:
df["Children in HHS Care"] = (
    df["Children in HHS Care"]
    .str.replace(",", "", regex=False)
    .astype(int)
)

In [13]:
df.dtypes

Date                                               datetime64[us]
Children apprehended and placed in CBP custody*           float64
Children in CBP custody                                   float64
Children transferred out of CBP custody                   float64
Children in HHS Care                                        int64
Children discharged from HHS Care                         float64
dtype: object

In [14]:
df.head()

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,2025-12-21,6.0,18.0,11.0,2484,14.0
1,2025-12-18,11.0,50.0,6.0,2472,16.0
2,2025-12-17,7.0,31.0,11.0,2481,10.0
3,2025-12-16,8.0,54.0,15.0,2468,9.0
4,2025-12-15,11.0,42.0,9.0,2470,7.0

### Business Conclusion

The "Children in HHS Care" column was originally stored as text because the values contained thousands separators (commas). These commas were removed and the column was converted into a numeric data type so that it can be used for statistical analysis, visualization, and machine learning forecasting models.

## Step 5 - Save Cleaned Dataset

In [15]:
df.to_csv(
    "../data/processed/HHS_UAC_Cleaned.csv",
    index=False
)